import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
} ){
  return (
      <html lang="en">
          <body className={`${inter.className}    min-h-screen m-auto`}>
              <Toaster position="top-right" />
              <Navbar />
              <main className="py-20  w-full">
                    {children}
                </main>
          </body>
      </html>
  );
}
